server:
  port: 8080  # default (prod / unspecified profile)

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:gigmework;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  mail:
    host: localhost
    port: 2525
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
app:
  reset:
    email:
      enabled: false
server:
  port: 8081  # dev profile port override

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/gigmework
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.example.com
    port: 587
    username: ${SMTP_USER:}
    password: ${SMTP_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  reset:
    email:
      enabled: true
